server {
    listen 80;
    server_name messanger.voclip.ru;
    return 301 https://$host$request_uri;
}

server{
    listen 443 ssl;
    server_name messanger.voclip.ru;

    ssl_certificate /etc/letsencrypt/live/messanger.voclip.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/messanger.voclip.ru/privkey.pem;
}
    location /api/ {
        proxy_pass http://backend:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
    
    location / {
        root /usr/share/nginx/html;
        index index.html;

        try_files $uri $uri/ /index.html;
    }
}